# Generated by Django 4.0.2 on 2022-11-15 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('downloaddocument', '0002_alter_potholedata_kms_covered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pothole_density',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p500', models.IntegerField()),
                ('p1000', models.IntegerField()),
                ('p1500', models.IntegerField()),
                ('p2000', models.IntegerField()),
                ('p2500', models.IntegerField()),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloaddocument.potholedata')),
            ],
        ),
    ]
